// Ícones pixel-art desenhados à mão em mapas ASCII. Substituem os emojis
// (que renderizam diferente em cada Android e quebravam a identidade visual).
// Uso: scene.add.image(x, y, "ico_heart").setScale(3)
import { PAL } from "./Palette.js";
import { Pix } from "./PixelArt.js";

// Legenda base — cada letra é uma cor da paleta
const L = {
  k: PAL.ink,
  w: PAL.white,
  l: PAL.cream,
  r: PAL.red2,
  R: PAL.red1,
  d: PAL.red0,
  o: PAL.org2,
  O: PAL.org1,
  h: PAL.org3,
  y: PAL.yel2,
  Y: PAL.yel1,
  z: PAL.yel3,
  e: PAL.g6,
  g: PAL.g5,
  G: PAL.g3,
  b: PAL.ice2,
  B: PAL.ice1,
  c: PAL.ice3,
  D: PAL.ice0,
  p: PAL.pur2,
  P: PAL.pur1,
  q: PAL.pur3,
  a: PAL.s4,
  s: PAL.s3,
  S: PAL.s2,
  x: PAL.s1,
  n: PAL.n3,
  N: PAL.n2,
  m: PAL.n4,
};

const MAPS = {
  heart: [
    ".kkkk..kkkk.",
    "kwrrrkkrrrrk",
    "kwrrrrrrrrRk",
    "krrrrrrrrrRk",
    "krrrrrrrrrRk",
    ".krrrrrrrRk.",
    "..krrrrrRk..",
    "...krrrRk...",
    "....krRk....",
    ".....kk.....",
  ],
  star: [
    ".....k.....",
    "....kzk....",
    "....kyk....",
    "kkkkkzykkkk",
    "kzzyzzzyyYk",
    ".kyyzzzyYk.",
    "..kyyyyYk..",
    "..kyyyyYk..",
    ".kyyYkyyYk.",
    ".kyYk.kYYk.",
    ".kkk...kkk.",
  ],
  coin: [
    "..kkkkk..",
    ".kzzyyyk.",
    "kzyyyyyYk",
    "kzyYyyyYk",
    "kyyYyyyYk",
    "kyyYyyyYk",
    "kyyyyyYYk",
    ".kyYYYYk.",
    "..kkkkk..",
  ],
  skull: [
    "..kkkkkk..",
    ".kllllllk.",
    "kllllllllk",
    "klkkllkkak",
    "klkkllkkak",
    "kllllllaak",
    ".kllkkllk.",
    "..klllaak.",
    "..klklkak.",
    "..kkkkkkk.",
  ],
  lock: [
    "..kkkkk..",
    ".kaaaaak.",
    ".kak.kak.",
    ".kak.kak.",
    "kkkkkkkkk",
    "kzyyyyyyk",
    "kyyykyyYk",
    "kyyykyyYk",
    "kYYYYYYYk",
    "kkkkkkkkk",
  ],
  pause: [
    "kkkk.kkkk",
    "kllk.kllk",
    "kllk.kllk",
    "kllk.kllk",
    "kllk.kllk",
    "kllk.kllk",
    "kllk.kllk",
    "kllk.kllk",
    "kkkk.kkkk",
  ],
  // "Assistir anúncio" — telinha com ▶ (símbolo universal de vídeo premiado)
  play: [
    ".kkkkkkkkkk.",
    "kaaaaaaaaaak",
    "kaxxwxxxxxak",
    "kaxxwwxxxxak",
    "kaxxwwwxxxak",
    "kaxxwwwwxxak",
    "kaxxwwwxxxak",
    "kaxxwwxxxxak",
    "kaxxwxxxxxak",
    "kaaaaaaaaaak",
    ".kkkkkkkkkk.",
    "...kk..kk...",
  ],
  fullscreen: [
    "kkkkk..kkkkk",
    "klllk..klllk",
    "klkkk..kkklk",
    "klk......klk",
    "kkk......kkk",
    "............",
    "............",
    "kkk......kkk",
    "klk......klk",
    "klkkk..kkklk",
    "klllk..klllk",
    "kkkkk..kkkkk",
  ],
  dash: [
    "kk....kk....",
    "kyk...kyk...",
    ".kyk...kyk..",
    "..kyk...kyk.",
    "..kyk...kyk.",
    ".kyk...kyk..",
    "kyk...kyk...",
    "kk....kk....",
  ],
  trophy: [
    "..kkkkkkkk..",
    "kkkzzyyyYkkk",
    "kykzyyyyYkyk",
    "kykzyyyyYkyk",
    ".kkkzyyyYkk.",
    "...kkyyYkk..",
    "....kyYk....",
    "....kyYk....",
    "...kkkkkk...",
    "..kYYYYYYk..",
    "..kkkkkkkk..",
  ],
  gem: [
    "...kk...",
    "..kegk..",
    ".keggGk.",
    "keggggGk",
    "kgggggGk",
    ".kgggGk.",
    "..kgGk..",
    "...kk...",
  ],
  chest: [
    ".kkkkkkkk.",
    "kmmmmmmmNk",
    "knnnnnnnNk",
    "kkkkyykkkk",
    "knnnyYnnNk",
    "knnnkknnNk",
    "knnnnnnnNk",
    "kkkkkkkkkk",
  ],
  gear: [
    "....kkk....",
    ".kk.kak.kk.",
    ".kakaaakak.",
    "..kaaaaak..",
    "kkaak.kaakk",
    "kaaak.kaaak",
    "kkaak.kaakk",
    "..kaaaaak..",
    ".kakaaakak.",
    ".kk.kak.kk.",
    "....kkk....",
  ],
  sound: [
    "....kk......",
    "...kak...l..",
    "kkkaak.l..l.",
    "kaaaak..l.l.",
    "kaaaak..l.l.",
    "kkkaak.l..l.",
    "...kak...l..",
    "....kk......",
  ],
  mute: [
    "....kk......",
    "...kak......",
    "kkkaak.r...r",
    "kaaaak..r.r.",
    "kaaaak...r..",
    "kkkaak..r.r.",
    "...kak.r...r",
    "....kk......",
  ],
  arrow: [
    "kk.....",
    "kzk....",
    "kyyk...",
    "kyyyk..",
    "kyyyyk.",
    "kyyyyYk",
    "kyyyYk.",
    "kyyYk..",
    "kyYk...",
    "kYk....",
    "kk.....",
  ],
  check: [
    "........kk",
    ".......kek",
    "kk....kegk",
    "kek..kegk.",
    "kgekkegk..",
    ".kgeegk...",
    "..kggk....",
    "...kk.....",
  ],
  // ---- Armas ----
  staff: [
    "........kk..",
    ".......khok.",
    "......khyyok",
    "......koyyok",
    ".......kook.",
    "......knkk..",
    ".....knk....",
    "....knk.....",
    "...knk......",
    "..knk.......",
    ".knk........",
    ".kk.........",
  ],
  aura: [
    "...kkkkk...",
    ".kkbbbbbkk.",
    ".kbbbwbbbk.",
    "kbbwbwbwbBk",
    "kbbbwwwbbBk",
    "kbwwwwwwwBk",
    "kbbbwwwbbBk",
    "kbbwbwbwbBk",
    ".kbbbwbbBk.",
    ".kkBBBBBkk.",
    "...kkkkk...",
  ],
  boomer: [
    "kkk.........",
    "khok........",
    "khook.......",
    ".khook......",
    "..khook.....",
    "...khookkkkk",
    "....khhhhhok",
    ".....kooooOk",
    "......kkkkkk",
  ],
  bolt: [
    "....kkkkk",
    "...kqpppk",
    "...kqppk.",
    "..kqppk..",
    "..kqpkkkk",
    ".kqppppqk",
    ".kkkkqpk.",
    "....kqpk.",
    "...kqpk..",
    "...kpk...",
    "..kpk....",
    "..kk.....",
  ],
  orb: [
    "....kkk....",
    "...kcbbk...",
    "...kbbBk...",
    "....kkk....",
    ".kkk...kkk.",
    "kcbbk.kcbbk",
    "kbbBk.kbbBk",
    ".kkk...kkk.",
  ],
  flame: [
    "....k.......",
    "...kok......",
    "...kohk.k...",
    "..kohhkkok..",
    "..kohyhkohk.",
    ".kohyyhhohk.",
    ".kohyzzyhhok",
    "kohyzzzzyhok",
    "kohyzzzzyhok",
    ".kohyzzyhok.",
    "..kkooooOk..",
    "....kkkk....",
  ],
  cloud: [
    "....kkkk....",
    "..kkllllk...",
    ".klllllllkk.",
    "kklllllllllk",
    "kllllllllllk",
    "kaallllllaak",
    ".kaaaaaaaak.",
    "..kkkkkkkk..",
  ],
  // ---- Passivas ----
  hourglass: [
    "kkkkkkkk",
    "knnnnnnk",
    ".kzzzzk.",
    "..kzzk..",
    "...kk...",
    "..kzyk..",
    ".kyyyyk.",
    "knnnnnnk",
    "kkkkkkkk",
  ],
  area: [
    "..kkkkkk..",
    ".keeeeeek.",
    "kekkkkkkek",
    "kek....kek",
    "kek.kk.kek",
    "kek.kk.kek",
    "kek....kek",
    "kekkkkkkek",
    ".keeeeeek.",
    "..kkkkkk..",
  ],
  projUp: [
    "....kk....",
    "...kzyk...",
    "..kzyyYk..",
    ".kzyyyyYk.",
    "kkkkyYkkkk",
    "...kyYk...",
    "...kyYk...",
    "...kyYk...",
    "...kkkk...",
  ],
  drop: [
    "....kk....",
    "...krrk...",
    "...krrk...",
    "..krrrrk..",
    ".krwrrrRk.",
    ".krwrrrRk.",
    "krrrrrrrRk",
    "krrrrrrRRk",
    ".krrrRRRk.",
    "..kkkkkk..",
  ],
  regen: [
    "...kkkk...",
    "...kegk...",
    "...kegk...",
    "kkkkegkkkk",
    "keeeeggggk",
    "kGGGggGGGk",
    "kkkkgGkkkk",
    "...kgGk...",
    "...kgGk...",
    "...kkkk...",
  ],
  crit: [
    "....kkk....",
    "..kkrrrkk..",
    ".krrkkkrrk.",
    ".krk...krk.",
    "krk..k..krk",
    "krk.krk.krk",
    "krk..k..krk",
    ".krk...krk.",
    ".krrkkkrrk.",
    "..kkrrrkk..",
    "....kkk....",
  ],
  magnet: [
    "kkkk..kkkk",
    "kaak..kaak",
    "krrk..krrk",
    "krrk..krrk",
    "krrk..krrk",
    "krrkkkkrrk",
    ".krrrrrrk.",
    "..kkkkkk..",
  ],
  shield: [
    "kkkkkkkkkk",
    "kaaaaSSSSk",
    "kaaaaSSSSk",
    "kaaaaSSSSk",
    "kSSSSaaaak",
    "kSSSSaaaak",
    ".kSSSaaak.",
    "..kSSaak..",
    "...kkkk...",
  ],
  clover: [
    ".kkk..kkk.",
    "keegkkeegk",
    "keggkkeggk",
    ".kkgkkgkk.",
    ".kkgkkgkk.",
    "keggkkeggk",
    "keGgkkgGGk",
    ".kkkkkkkk.",
    "....kGk...",
    "....kkk...",
  ],
  plus: [
    "..kkk..",
    "..kek..",
    "kkkekkk",
    "keeeeek",
    "kkkekkk",
    "..kek..",
    "..kkk..",
  ],
  close: [
    "kk...kk",
    "klk.klk",
    ".klklk.",
    "..klk..",
    ".klklk.",
    "klk.klk",
    "kk...kk",
  ],
  sword: [
    "........kkk",
    ".......kalk",
    "......kalk.",
    ".....kalk..",
    ".kk.kalk...",
    ".kykalk....",
    "..kyak.....",
    ".kykyk.....",
    "kNk.kyk....",
    "kk...kk....",
  ],
};

// Recolorações (mesmo desenho, outra "tinta") — evoluções e passivas
const RECOLOR = {
  bolt_gold: { base: "bolt", swap: { q: "z", p: "y" } },
  heart_ice: { base: "heart", swap: { r: "b", R: "B", w: "c" } },
  flame_pink: { base: "flame", swap: { o: "r", h: "z", O: "R" } },
  cloud_hot: { base: "cloud", swap: { l: "h", a: "o" } },
  dash_green: { base: "dash", swap: { y: "e" } },
  heart_plus: { base: "heart", swap: {} },
  arrow_left: { base: "arrow", flip: true },
  orb_frost: { base: "orb", swap: { b: "c", B: "b", c: "w" } },
  flame_red: { base: "flame", swap: { o: "R", h: "r", y: "o", O: "d" } },
};

export function registerIcons(scene) {
  for (const [key, rows] of Object.entries(MAPS)) {
    Pix.fromMap(rows, L).register(scene, "ico_" + key);
  }
  for (const [key, def] of Object.entries(RECOLOR)) {
    const rows = MAPS[def.base].map((row) =>
      [...row].map((ch) => def.swap?.[ch] ?? ch).join(""),
    );
    const p = Pix.fromMap(rows, L);
    if (def.flip) {
      const f = new Pix(p.w, p.h);
      f.blit(p, 0, 0, true);
      f.register(scene, "ico_" + key);
    } else p.register(scene, "ico_" + key);
  }
}

// Ícone por arma (chave de WEAPONS) e por passiva (id de PASSIVES)
export const WEAPON_ICON = {
  STAFF: "ico_staff",
  AURA: "ico_aura",
  BOOMER: "ico_boomer",
  CHAIN: "ico_bolt",
  ORB: "ico_orb",
  FLAME: "ico_flame",
  VAPOR_STORM: "ico_cloud_hot",
  OVERLOAD_X: "ico_bolt_gold",
  WINTER_HEART: "ico_heart_ice",
  PHOENIX: "ico_flame_pink",
  GLACIER: "ico_orb_frost",
  INFERNO: "ico_flame_red",
};

export const PASSIVE_ICON = {
  hp: "ico_heart",
  speed: "ico_dash_green",
  cooldown: "ico_hourglass",
  area: "ico_area",
  proj: "ico_projUp",
  lifesteal: "ico_drop",
  regen: "ico_regen",
  crit: "ico_crit",
  magnet: "ico_magnet",
  armor: "ico_shield",
  luck: "ico_clover",
};
